### ISSUE TITLE
When getting releases, ratings with "count" field breaks hashie

### ISSUE THREAD

**Issue by rmammina** [buntine/discogs#48] opened 2017-03-10 04:32 UTC

**Comment by rmammina** [comment] 2017-03-10 04:32
```
You are setting a key that conflicts with a built-in method Hashie::Mash#count defined in Enumerable. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
NameError: undefined method `type_' for class `Hashie::Mash'
```

**Comment by buntine** [comment] 2017-03-10 05:07
Thanks,  I will investigate a fix.

**Comment by buntine** [comment] 2017-03-10 10:09
Ok, I've pushed a fix for this that sanitizes the input by renaming "count" to "total" before parsing into a Hashie object.

But, as this is a breaking change, I have not yet published the fix to Rubygems as it could wreak carnage with some current users.

I'm going to have a think about the best way to go forward before I publish anything as I'm not sure whether I will bump the major version and deprecate "count" or whether I'll provide temporary backwards-compatibility.

I'll leave this issue open for now.

**Comment by buntine** [comment] 2017-03-10 10:29
Ok, I decided to add a backwards-compatibility fix and raise an additional DEPRECATED warning. This has been published to Rubygems a v2.3.0

So, for now you will still see the warning(s), but you can safely ignore them for now. Soon they will both disappear once I've given users enough time to adapt to the change and I release a new major version with the breaking change in it.

Thanks again. :)

**Comment by rmammina** [comment] 2017-03-10 15:22
Thanks, note though that this was still breaking for certain releases. I ended up locking Hashie at 3.4.6 for it to work. 
![image](https://cloud.githubusercontent.com/assets/978280/23800692/37746756-0562-11e7-86ef-9a2b636a9db4.png)

**Comment by buntine** [comment] 2017-03-11 00:37
Oh,  that's interesting.  Can you show me exactly what you are doing to receive that Nameerror? The behaviour I was seeing only resulted in a warning. I'll reopen the issue until i can confirm there are no runtime errors occuring here.

**Comment by buntine** [comment] 2017-03-17 22:50
Closing due to no response. I can't replicate the issue.

**Closed by buntine** 2017-03-17 22:50 UTC

**Comment by VinylVault** [comment] 2019-07-01 11:47
Sorry to reopen .... but I'm getting this also. when accessing `get_users_folders`

```
You are setting a key that conflicts with a built-in method Hashie::Mash#count defined in Enumerable. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
```
I've tried addressing both `count` and `total`

`total` gives a blank entry
`count` gives the numeral 4, for all results (none of the folders have 4 releases in them so i dont know where this is coming from)

**Comment by buntine** [comment] 2019-07-01 12:16
Can you provide some example code to replicate this problem?

Make sure you read the discogs API docs so you know exactly what the API
will respond with. The get_user_folders method will return a key called
"folders" whose value is an array of folder details. Any time you see
'count', you should be replacing it with 'total'.

**Comment by VinylVault** [comment] 2019-07-01 13:24
this is what i'm doing

```
@discogs = Discogs::Wrapper.new("Test OAuth", user_token: "<removed>")
@user = @discogs.get_identity
@shelfunit = @discogs.get_user_folders(@user.username)
```
For each folder I get the error above, then it displays the API call.

When I do this for a release, I get a message saying `count` is replaced by `total` there is no message like that on folders

**Comment by buntine** [comment] 2019-07-02 00:15
Hey there,

This is an interesting problem. The count->total sanitization should be running on all API endpoints so I am not sure why its not working right now. I'll need to look a bit deeper into it.

But here is what you can do right now:

1) The "error" is actually just a warning. You can ignore it for now.
2) Use Ruby's attribute accessor in order to get the "count":

```
@discogs = Discogs::Wrapper.new("Test OAuth", user_token: "<removed>")
@user = @discogs.get_identity
@shelfunit = @discogs.get_user_folders(@user.username)
@folders = @shelfunit.folders
@first_folder_count = @folders.first['count']
```
